const assert = require('node:assert/strict');
const C = require('./core.js');
let s = C.fresh();
for(let i=0;i<9;i++) s=C.addMovie(s,{title:'Film '+i,year:'2026'},()=>0);
assert.equal(s.started,false,'picker stays locked under ten');
assert.equal(s.currentId,null);
s=C.addMovie(s,{title:'Film 9',year:'2026'},()=>0);
assert.equal(s.started,true,'ten choices activate picker');
assert.equal(s.currentId,'title:film 0|2026','first random choice persists');
const selected=s.currentId;
s=C.addMovie(s,{title:'Film 10',year:'2026'},()=>0.99);
assert.equal(s.currentId,selected,'extra choices do not reroll current');
s=C.pickNext(s,()=>.99);
assert.equal(s.currentId,selected,'refresh does not reroll current');
assert.throws(()=>C.addMovie(s,{title:'Film 9',year:'2026'}),/already/,'duplicates rejected');
assert.throws(()=>C.addMovie(s,{tmdbId:9123,title:'Film 9',year:'2026'}),/already/,'manual and TMDB duplicates rejected');
assert.throws(()=>C.finishCurrent(s,11,'Good'),/score/,'invalid scores rejected');
assert.throws(()=>C.finishCurrent(s,8,'   '),/review/,'written review required');
s=C.finishCurrent(s,8,'Brilliant evening!',()=>0,'2026-10-08T17:00:00Z');
assert.equal(s.history.length,1,'review saved in diary');
assert.equal(s.history[0].rating,8);
assert.equal(s.currentId,'title:film 1|2026','next film automatically picked');
assert.equal(s.queue.length,10,'review frees a slot');
s=C.editReview(s,s.history[0].id,9,'Even better on reflection');
assert.equal(s.history[0].rating,9);
assert.equal(C.stats(s).watched,1);
assert.equal(C.normaliseState(JSON.parse(JSON.stringify(s))).currentId,s.currentId,'state survives reload');
for(let i=11;i<21;i++) s=C.addMovie(s,{title:'Film '+i},()=>.4);
assert.equal(s.queue.length,20,'queue accepts 20 at once');
assert.throws(()=>C.addMovie(s,{title:'Too many'}),/full/,'queue never exceeds 20');
const last=s.currentId;
s=C.removeMovie(s,last,()=>0);
assert.equal(s.queue.length,19);
assert.ok(s.currentId && s.currentId!==last,'remove current chooses another');
assert.equal(C.normaliseState({queue:[{title:''}],history:[]}).queue.length,0,'malformed imports filtered');
console.log('PASS: 18 assertions, picker threshold, persistent choice, fresh picks, review progression, edits, limit, removal and validation.');